project:
  type: book

book:
  title: "Aide-memoire"
  author: "Ewen Gallic"
  date: "5/27/2023"
  repo-url: https://github.com/3wen/aide-memoire
  chapters:
    - index.qmd
    - part: R
      chapters:
      - colours.qmd
      - color_words_markdown.qmd
    - part: Git
      chapters:
      - git-rstudio.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: source

