project:
  type: book

book:
  title: "Aide-memoire"
  author: "Ewen Gallic"
  date: "5/27/2023"
  repo-url: https://github.com/3wen/aide-memoire
  chapters:
    - index.qmd
    - part: R
      chapters:
      - colours.qmd
      - color_words_markdown.qmd
    - part: Quarto
      chapters:
      - quarto_equation_colors.qmd
    - part: Git
      chapters:
      - git-rstudio.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    include-in-header:
    - text: |
        \usepackage{xcolor}
        \definecolor{wongBlue}{RGB}{0, 114, 178}

editor: source
