project:
  type: book
  output-dir: docs

book:
  title: "Aide-mémoire"
  author:
  - name: Ewen Gallic
    orcid: 0000-0003-3740-2620
    affiliations:
      - name: Aix-Marseille School of Economics, Aix-Marseille Univ.
  date: "12/26/2024"
  chapters:
    - index.qmd
    - part: R
      chapters:
      - r_colour_palettes.qmd
      - r_graphs_color_words_markdown.qmd
      - r_base_plot_latex.qmd
      - r_ggplot2.qmd
    - part: Quarto
      chapters:
      - quarto_equation_colors.qmd
      - quarto_emojis.qmd
    - part: Git
      chapters:
      - git-rstudio.qmd
    - references.qmd
  navbar:
    right:
      - icon: github
        href: https://github.com/3wen/aide-memoire
        aria-label: GitHub

bibliography: ./references.bib

fig-cap-location: top

format:
  html:
    from: markdown+emoji
    theme: cosmo
    highlight-style: github
    html-math-method: mathjax
    include-in-header:
    - file: mathjax-color.html

editor: source
