project:
  type: book

book:
  title: "Aide-mémoire"
  author: "Ewen Gallic"
  date: "5/27/2023"
  repo-url: https://github.com/3wen/aide-memoire
  chapters:
    - index.qmd
    - part: R
      chapters:
      - r_colour_palettes.qmd
      - r_graphs_color_words_markdown.qmd
    - part: Quarto
      chapters:
      - quarto_equation_colors.qmd
      - quarto_emojis.qmd
    - part: Git
      chapters:
      - git-rstudio.qmd
    - references.qmd

bibliography: references.bib

from: markdown+emoji


format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    pdf-engine: lualatex
    include-in-header:
    - text: |
        \usepackage{emoji}
        \usepackage{xcolor}
        \definecolor{wongBlue}{RGB}{0, 114, 178}

editor: source
